name: Android CI

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'gradle/**'
      - '**/*.gradle*'
      - 'settings.gradle*'
      - 'build.gradle*'
      - 'gradlew*'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'gradle/**'
      - '**/*.gradle*'
      - 'settings.gradle*'
      - 'build.gradle*'
      - 'gradlew*'

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true



jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      # If you keep google-services.json as a GitHub secret, write it out here.
      # In repo Settings → Secrets → Actions → add GOOGLE_SERVICES_JSON (the full JSON string).
#      - name: Create google-services.json (optional)
#        if: ${{ secrets.GOOGLE_SERVICES_JSON != '' }}
#        run: |
#          mkdir -p app
#          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build, unit tests, and lint for debug
      - name: Build & Test
        run: ./gradlew --no-daemon testDebugUnitTest assembleDebug

      - name: Android Lint
        run: ./gradlew --no-daemon lintDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
